### ISSUE TITLE
Feature: Better resize

### ISSUE THREAD

**Issue by venatiodecorus** [blocktronics/moebius#100]
Would be great to be able to drag edge of canvas or something to resize

**Comment by andyherbert** [comment]
Thanks for your feedback.

I'm not sure about resizing using a responsive UI gadget, it would be fairly complicated to implement, be restricted to the size of the screen, and wouldn't offer any significant benefits to the current implementation. If you could tell me about your motivation for replacing the current tool, then maybe we could figure out an alternative solution.
