### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by Kirkman** [blocktronics/moebius#103]
Could you add tooltips when hovering over tools in the toolbar? 

I can't quite figure out what that third tool is, so it'd probably be useful for dummies like me.

**Comment by andyherbert** [comment]
It's a tool to shift a text position to one of the half-vertical blocks. Clicking on the left button and right button makes some assumptions over what the foreground and background colours should be and makes a left or right vertical block accordingly.

That being said, I'm not sure if having a tooltip with "Vertical Block Shifter" would offer much in the way of explanation, and anything more explanative would better be suited to documentation, and I'm even lazier with prose than I am with programming.
