### ISSUE TITLE
Bug: failed to load, ansi art example

### ISSUE THREAD

**Issue by bengarrett** [blocktronics/moebius#104]
Hi, I know Moebius is an editor rather than a viewer, so I don't know if this is relevant. But I encountered this attached piece of art fails to load.

[BT-TBR.zip](https://github.com/blocktronics/moebius/files/3634139/BT-TBR.zip)

![Capture](https://user-images.githubusercontent.com/513842/65298348-85608b00-dbae-11e9-9ad5-747c3e2cac65.PNG)

![Capture2](https://user-images.githubusercontent.com/513842/65298354-898ca880-dbae-11e9-983d-bcb03e9680f7.PNG)

**Comment by andyherbert** [comment]
The Sauce record is screwed, for instance it reports the file size as 211 bytes and the amount of the ansi as 25 rows high. If you remove the last 129 bytes of the file then it appears to render as shown there.
