### ISSUE TITLE
Support for .msg, .asc

### ISSUE THREAD

**Issue by AshleyStone** [blocktronics/moebius#107]
These are ANSI files that use the CTRL+A format, commonly used on some BBS systems like Synchronet.

Attached an example file with the extension renamed sto something github would allow:
[bullseye.txt](https://github.com/blocktronics/moebius/files/3714373/bullseye.txt)

**Comment by andyherbert** [comment]
This has been brought up before, and I don't think I've changed my mind.

https://github.com/blocktronics/moebius/issues/64
