### ISSUE TITLE
Allow Variable Size Paint Brush Size

### ISSUE THREAD

**Issue by christianvozar** [blocktronics/moebius#113]
Allow adjusting of the paint brush to sizes larger than half-block and full block. Currently, PabloDraw allows selecting block sizes 1-9.

**Comment by christianvozar** [comment]
@andyherbert Tagging you on this because mostly you have the domain knowledge needed to implement this the fastest and is the most requested feature from the hold-outs on PabloDraw. Misfit, TCF, and several others have specifically told me this is the missing feature needed to get them on Moebius and away from PD.

They color and draw with the variable sized brush (1-9 sized in PD). They also need the ability to change what character they are drawing with. In Misfit's case he will draw a large grey background and use different shade blocks to sketch on top of that, sometimes with a 2x2 or 3x3 block size.

**Comment by bart-d** [comment]
![image](https://user-images.githubusercontent.com/6034441/81426643-c74c3a80-9159-11ea-9e30-e1078c5e1f34.png)

added in 9f1e5f7c8cde0c7c758d29e20a5f7a2c1b68c9da, thanks!
