### ISSUE TITLE
Bug: Pressing ESC several times quickly causes a color selector to stick

### ISSUE THREAD

**Issue by phenomprod** [blocktronics/moebius#127]
I've run across this bug when hitting ESC twice or more times quickly.  I usually run into it when I accidentally hit ESC twice.  The Color Selector pops up but even after you select a color it remains onscreen and doesn't disappear.  The only way to get passed this issue is by exiting the program and launching it again as a new instance.

![image](https://user-images.githubusercontent.com/62371015/80320106-4429fc80-87c9-11ea-8821-f097255db3f7.png)

**Comment by bart-d** [comment]
already fixed by 461cd42f42aebdfa4d479d39e835edec919dd4a3
