### ISSUE TITLE
File > Open or clicking Open from the start screen crashes the app

### ISSUE THREAD

**Issue by essteewhy** [blocktronics/moebius#136]
Attached error i get, i deleted all the appdata folders, still won't install.  Ran as admin, still won't install.  Portable version doesn't run either!

![moebius_error](https://user-images.githubusercontent.com/34491540/80888790-b6905600-8c7b-11ea-9b13-d4d7a57bd16d.png)

![image](https://user-images.githubusercontent.com/34491540/80889527-e93a4e80-8c7b-11ea-8f9f-8883b3ca5c79.png)

**Comment by andyherbert** [comment]
I had a quick look at this and I think it may be because bundling arm64 code with the executable might be causing the issue. Can you please reinstall from the webpage and update this issue? Thanks.

**Comment by essteewhy** [comment]
Install's perfectly fine now!  thanks!!

**Comment by andyherbert** [comment]
That's strange. Any better luck with the portable executable?

**Comment by essteewhy** [comment]
Portable version acts the same as the installed one.

**Comment by andyherbert** [comment]
Will a file open if double click it in Windows explorer?

**Comment by essteewhy** [comment]
yes, that works..  File -> Open still crashes it

just an aside, is there anyway force the .ans extension in Win10 to open with Moebius? it always asks..

**Comment by andyherbert** [comment]
I'm not sure. Windows isn't really something I know a lot about, I build Moebius on a Mac and sort of cross my fingers when it comes to building for other platforms. I'll take a look tomorrow at the open file bug tomorrow when I'm in a better position to boot Windows up.

**Comment by essteewhy** [comment]
Ok sounds good.. Using Windows Explorer to open files does work, and File -> Save does work so i'm not dead in the water :)  Thanks for checking into this so fast..!

**Comment by andyherbert** [comment]
What about File > Save As... ?

**Comment by essteewhy** [comment]
Yep that works, very odd.  Also just tried setting my Backup Folder in the settings, it also crashes it.

**Comment by andyherbert** [comment]
Alright, thanks for checking for me. I'll update this issue when I've taken a further look, at least you have a workaround for now.

**Comment by essteewhy** [comment]
Ok so now everything is working.  After i used File -> Save as ..  it all the open buttons are working.

**Comment by andyherbert** [comment]
Well, at least that's something. If the problem reoccurs then let me know and I'll take a look tomorrow in any case.

**Comment by andyherbert** [comment]
I had another look, this time on an actual Windows machine and couldn't reproduce. If this reoccurs then let me know! I'll update the title of the issue in case anyone else wants to contribute.

**Comment by essteewhy** [comment]
was yours a fresh install or an update to a previous install?  I was pondering this as well if the same problem would occur..  mine was an update to a previous install

**Comment by andyherbert** [comment]
I installed over a previous version.

**Comment by bart-d** [comment]
I can't reproduce this on win7/64-bit and not non win10/64-bit (1909). Tried woth both the installer and the portable version.

**Comment by essteewhy** [comment]
very odd, i posted this issue on the b7 discord and mypalgoo had the same error i did..  really don't know !

**Comment by bart-d** [comment]
> very odd, i posted this issue on the b7 discord and mypalgoo had the same error i did.. really don't know !

he was talking about the initial installer issue (cfr screenshot in the first post in this thread). i didn't see him mention the _File > Open_ issue at all tbh

**Comment by andyherbert** [comment]
My best guess is that the requester was defaulted to a folder that no longer exists and then the error started or cascaded down from there.

**Comment by essteewhy** [comment]
> > very odd, i posted this issue on the b7 discord and mypalgoo had the same error i did.. really don't know !
> 
> he was talking about the initial installer issue (cfr screenshot in the first post in this thread). i didn't see him mention the _File > Open_ issue at all tbh

Yeah i don't think he got that far, the error in the first screenshot was before Andy made a code change.

**Comment by essteewhy** [comment]
> My best guess is that the requester was defaulted to a folder that no longer exists and then the error started or cascaded down from there.

Somehow only affected a few of us i guess? I don't know, just glad i can continue to work on projects!  :)  again i appreciate you looking at this so quickly!

**Comment by bart-d** [comment]
> 
> 
> My best guess is that the requester was defaulted to a folder that no longer exists and then the error started or cascaded down from there.

I tried this, but it drops me in %localappdata%\Local\Programs\moebius when trying to open a file. Anyway, looks like even the requester can't reproduce it anymore, we can wait for it to pop again, if ever.

**Comment by andyherbert** [comment]
I'm assuming now this was a one-time event. Also, I should probably stagger updates in future.
