### ISSUE TITLE
Implement time spent per project

### ISSUE THREAD

**Issue by essteewhy** [blocktronics/moebius#137]
Figure it would be cool to see how much time you've spent on each art piece..

**Comment by andyherbert** [comment]
I'm not sure how this metadata could be saved alongside the file.

**Comment by andyherbert** [comment]
I'm going to close this, it's a nice idea in theory but unlikely to be accurate if the metadata issue could be addressed. The subject of a custom file format has been brought up many times, but the scene is wedded to the .ans file format. Plus there's an issue that any implementation wouldn't conform to everyone's expectations (does total time mean whilst the application is open? that stuff is being drawn to it? time from starting to finishing a project?).
