### ISSUE TITLE
Server: save backups in ANSI format

### ISSUE THREAD

**Issue by bart-d** [blocktronics/moebius#138]
Save the server hourly backups in ANSI format instead of a comma separated list of ASCII codes.

**Comment by andyherbert** [comment]
This is odd, I just tried and it appears to be ansi format. Are there any particular sequence that appear comma separated?

**Comment by bart-d** [comment]
it's the entire file, numeric ASCII codes comma separated. I've attached an example ( 
[server1588464045.zip](https://github.com/blocktronics/moebius/files/4569745/server1588464045.zip)). This is the most recent backup of the Moebius server on 16c (visible here: https://16colo.rs/servers/)

I convert it back to ANSI through splitting by comma and doing a chr on every value.

**Comment by andyherbert** [comment]
That's strange. I saved the 16c server session locally and used it as a server session myself and the backup still saved as expected. I've pushed a change to explicitly save bytes in binary representation. If you can reproduce this bug then I'd be grateful if you can try this change.

**Comment by bart-d** [comment]
![image](https://user-images.githubusercontent.com/6034441/80908811-42a98880-8d23-11ea-844b-1a710ce8d301.png)

Yes, even with the patch I can reproduce it. Started out with an empty file. Haven't tried on any other OS than Linux though.

**Comment by bart-d** [comment]
![image](https://user-images.githubusercontent.com/6034441/80908930-41c52680-8d24-11ea-9e6f-3a1b058f704b.png)

works fine on MacOS apparently

**Comment by andyherbert** [comment]
Are the versions of node on both platforms identical?

**Comment by bart-d** [comment]
> Are the versions of node on both platforms identical?

v8.10.0 on Linux vs. v12.16.2 on MacOS. I'll try upgrading node on Linux.

**Comment by bart-d** [comment]
upgrading to node v12 fixes the issue. thanks! :)
