### ISSUE TITLE
Provide "Favorites" of Servers to Connect

### ISSUE THREAD

**Issue by christianvozar** [blocktronics/moebius#142]
Application would provide a list of favorite servers to connect for those artists with many servers they want to remember.

Shout out to @bart-d for the last server being populated, that made me think a favorites drop down would really enhance this.

**Comment by andyherbert** [comment]
I think the obvious (and least work for me) way to do this is to provide "add to bookmarks", and have a Bookmarks menu like a web browser that stores the user, server, route, and password.

The annoying part would be implanting the UI to rearrange and edit the list.

**Comment by andyherbert** [comment]
Could multi-purpose the current "Connect to server" requester with a listview and save/delete button which would provide the minimum amount of functionality

**Comment by christianvozar** [comment]
Least amount of work is ideal.

**Comment by andyherbert** [comment]
Yeah, I vote to drop it too. I thought it wouldn't matter but it's trivial to roll back changes anyway, and I would prefer people actually try the changes in ways that might break the app rather than try and reason about the code.

**Comment by bart-d** [comment]
![image](https://user-images.githubusercontent.com/6034441/81426405-6f153880-9159-11ea-9f25-1f5322fffb99.png)

added in 16ea7b9150642873d851ca13dbdaa63c6aac9a70, thanks!
