### ISSUE TITLE
Convert ice-colours to normal feature

### ISSUE THREAD

**Issue by andyherbert** [blocktronics/moebius#145]

**Comment by bart-d** [comment]
Very good idea imho, would certainly overcome some hair pulling 😄 it certainly is handy for those who know how it works but accidently switch fg/bg but those who have used a foreground color as background color, how would you convert those? Remain blinking? Nearest neighbour?

**Comment by andyherbert** [comment]
Yeah, the idea I have is to open a new document window and try to be just reduce the bg colour to the first 8 for those where there's no possible alternative.

**Comment by bart-d** [comment]
![image](https://user-images.githubusercontent.com/6034441/81563756-ff8c8c80-9396-11ea-8773-b944bdff23a0.png)

after checking dcc27f175a0575facfb2aaebf38a65e88fd554cd: on the left the original document with ice colors, on the right one with ice colors removed. As you can see the glyphs with 'double foreground colors' are adapted as expected, to the nearest possible background color.

However there is a case that occurs frequently when fg/bg are accidently switch and then shade blocks and/or horizontal/vertical halfblocks are used. In the example above are only shade blocks. in this case only the background color is adapted, while the expection might be that in this case fg/bg should be switched and alos glyphs  F1/F3, F5/F6 and F7/F8 to be switch. In the left screenshot at the bottom you can see how these are almost equal in visualization.

**Comment by andyherbert** [comment]
It was supposed to flip chars, but I screwed up. I've just pushed a change to hopefully fix it.

**Comment by bart-d** [comment]
![image](https://user-images.githubusercontent.com/6034441/81588115-55256100-93b8-11ea-8e97-7651a40e6e6b.png)

looking good! going to try this on real artwork :)

**Comment by bart-d** [comment]
looks good to me :)

https://16colo.rs/pack/impure73/arl-revision.ans

| i | r | b |
| :------------ | :------------ | :------------ |
| ![arl-revision-ice](https://user-images.githubusercontent.com/6034441/81598179-3084b580-93c7-11ea-80a6-4a0fa9958adc.png)|![arl-revision-icerm](https://user-images.githubusercontent.com/6034441/81598240-45614900-93c7-11ea-878e-072695203294.png)|![arl-revision-blink](https://user-images.githubusercontent.com/6034441/81598289-5611bf00-93c7-11ea-81e4-9b94a24ae96f.png)|

https://16colo.rs/pack/blocktronics_1980/iks-tfots.ans
| i | r | b |
| :------------ | :------------ | :------------ |
|![iks-tfots-ice](https://user-images.githubusercontent.com/6034441/81601813-cae6f800-93cb-11ea-9144-14bf189c55ff.png)|![iks-tfots-removed](https://user-images.githubusercontent.com/6034441/81601830-d2a69c80-93cb-11ea-9b50-43c3e04b292a.png)|![iks-tfots-blink](https://user-images.githubusercontent.com/6034441/81601841-d89c7d80-93cb-11ea-909f-73d07768435d.png)|
