### ISSUE TITLE
Feature Request: Create/Edit/Delete bookmarks for connecting to different Moebius Servers

### ISSUE THREAD

**Issue by christiansacks** [blocktronics/moebius#193]
It would be neat to have a bookmark manager that can save the connection information for various different Moebius servers so that I don't have to keep that in a separate file and then copy/paste to connect to one.

**Comment by bart-d** [comment]
This feature was added to Moebius over one year ago (https://github.com/blocktronics/moebius/issues/142) maybe you need to upgrade to the latest version?
