### ISSUE TITLE
Enhancement: Zoom Should Affect Only Drawing Canvas

### ISSUE THREAD

**Issue by christianvozar** [blocktronics/moebius#21]
Zoom currently resizes the entire viewable window but should only affect the drawing canvas, not the high res preview and drawing tools.

**Comment by andyherbert** [comment]
Not sure if this is possible without reinventing the wheel. The zoom function is provided by electron and works on the entire webview. If you look at slack, discord, vscode, etc they zoom the entire UI relative to each other, it is possible but would require a lot of work, probably more than I would want to put in.

**Comment by calcmandan** [comment]
I second this. Is it possible to design the UI such that the elements along the side are in their own frame
