### ISSUE TITLE
Bug: Fill Tool Does Not Include Half/Side Blocks

### ISSUE THREAD

**Issue by christianvozar** [blocktronics/moebius#24]
This example was a light grey "brain" that I filled "dark grey" and the side blocks were not included.

<img width="355" alt="Screen Shot 2019-06-13 at 4 21 48 PM" src="https://user-images.githubusercontent.com/419688/59471150-74f28480-8df7-11e9-958b-522003ce785f.png">

**Comment by andyherbert** [comment]
I've made it slightly better and it's not perfect but I don't think I want to make the flood fill any more complex than it already is.
<img width="577" alt="Screenshot 2019-06-15 at 13 53 57" src="https://user-images.githubusercontent.com/25620/59551689-3387e380-8f75-11e9-8343-9d12b68f36f7.png">
