### ISSUE TITLE
TheDraw font support.

### ISSUE THREAD

**Issue by ellisgl** [blocktronics/moebius#34]
It would be cool if we could get TheDraw font support.

**Comment by andyherbert** [comment]
Thanks for your feedback! I have read this but keeping it on hold because it would be quite a bit of work working out the specifics of the file format, and there's a few other things that I want to implement first.

**Comment by andyherbert** [comment]
I've had a look at this, and even taking into account Roy/SAC's analysis of the file format, there would still be a bit of reverse engineering required, and I'm not sure I am motivated enough to start that particular task. There's also the issue that if I implement the feature then the expectation would be to also include a large selection of fonts with the application, I'm sure there would be no legal repercussions from doing so, but I'm not sure I ideologically support the idea considering that some of these may have been ripped from artist's work in the past.

**Comment by ellisgl** [comment]
How about creating your own font system?

**Comment by andyherbert** [comment]
I could, but that still wouldn't motivate me from implementing it. I don't think there would be any ANSI artists who would actually use it either.

**Comment by ftoledo** [comment]
TDF support will be great feature.
Maybe you can use the syncdraw source code
https://gitlab.synchro.net/main/sbbs/-/tree/master/src/syncdraw
