### ISSUE TITLE
Frame drawing characters as well as blocks.

### ISSUE THREAD

**Issue by crenshawthorpe** [blocktronics/moebius#54]
I understand your focus here is on block drawing, but I'll tell you, you're just a hair away from being a full-bore, all-purpose ANSI editor even for text-based stuff.  One thing I'd love to see is an ability to select F1-F10 sets of characters beyond just the blocks you have now, and include things like the frame/box drawing CP437 characters.  I know these are not used in block art but as I say, I've been using it for other things.

**Comment by andyherbert** [comment]
It’s not very well documented, but you cam switch between different function key selections by hitting Ctrl comma and period.

**Comment by andyherbert** [comment]
This will be configurable in the new version.
