### ISSUE TITLE
Please support Synchronet CTRL-A files (.asc)

### ISSUE THREAD

**Issue by ftoledo** [blocktronics/moebius#64]
When I open synchronet ctrl-a file :

![imagen](https://user-images.githubusercontent.com/95441/62262756-3e48eb80-b3f0-11e9-87ae-3d932faca8bf.png)

http://wiki.synchro.net/custom:ctrl-a_codes

Thanks!

**Comment by andyherbert** [comment]
Hi. I've had a look at this and there's a few things that really discourage me from implementing this. 

Firstly the 'Ctrl-A' character is a control character, but it's not outside the realm of possibility that it could be used in artwork, which means some logic would be required to determine if a file is meant for Synchronet or not, and I don't particularly want to deal with adding complexity to parsing and rendering ANSI files.

Secondly .asc is an extension that's used by some artists, and is registered as an associated filetype already in-app,  to specify that a piece of work is exclusively text and omits any escape sequences, so I'd have to work around that issue as well.

Thirdly, and perhaps more importantly there already exists a tool to deal with this problem: http://wiki.synchro.net/util:ans2asc. It would be possible for me to implement it given enough time and motivation, but as this is something I would very likely never use I doubt that it would be any better than the pre-existing solution.

Thanks for your feedback!
