### ISSUE TITLE
cant run on debian

### ISSUE THREAD

**Issue by josx** [blocktronics/moebius#72]
I got:

```moebius: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory```

I have tested using current version 1.0.17 :

- Building deb file locally
- Installing and running provided deb file

In both cases libffmpeg.so is in opt dir (BTW I think it is not good enaugh to to copy or add opt dir to my local LD_LIBRARY_PATH manually).
Also not running if i do it  from ```./linux-unpacked```

**Comment by andyherbert** [comment]
I've silently updated the .deb package on the website at http://www.andyh.org/moebius/Mœbius.deb

Could you please confirm if this works as intended?

**Comment by josx** [comment]
Hey @andyherbert, yes right now it is working pretty well. :+1: 

How did you solve it?

**Comment by andyherbert** [comment]
I tried running it and had no joy either, so instead of building on MacOS I used Debian in a VM instead. It seemed to work fine, so I'm not actually sure what the cause of the problem was.

**Comment by josx** [comment]
ok, so let close this issue.
great work
