### ISSUE TITLE
Splash Screen request

### ISSUE THREAD

**Issue by mard0** [blocktronics/moebius#75]
Love the splash screen but an option in setting to minimise or close when app opens would be cool.

**Comment by andyherbert** [comment]
Just wondering what a workable alternative would be. MacOS users have an application menu, but I also have to consider Windows and Linux users, so I have to show some form of UI when the application starts.

**Comment by mard0** [comment]
I'm on Windows currently myself. The splash screen is great as is, I was thinking it would be nice if it dropped out of the way after selecting open or load and the editor window opens.

I never have enough desktop real estate. Now that I think about it though that might interfere with the networking function?

**Comment by andyherbert** [comment]
I'll have to look into whether I can minimise it after a new window is opened. If I close all the windows on Windows it ends the application, and that might cause a frustration if someone, for example, opens a document to work on and then closes the window before trying to create a new one.

**Comment by andyherbert** [comment]
This is about to be included in an update imminently.
