### ISSUE TITLE
Keybindings: Support for non-US keyboards

### ISSUE THREAD

**Issue by luminde** [blocktronics/moebius#77]
The 'Cycle func. keys', which are currently set to 'CTRL+<' and 'CTRL+>' don't work on keyboards with a nordic layout as the '<' and '>' symbols are on the same key.

**Comment by andyherbert** [comment]
The cheat sheet is a bit misleading, the binding is actually for comma and period, but I chose to signify < and > because it worked better mnemonically.

**Comment by andyherbert** [comment]
btw, you thought about joining a text mode art group such as Blocktronics? I really liked that free-fall piece you created for LayerOne!

**Comment by luminde** [comment]
> The cheat sheet is a bit misleading, the binding is actually for comma and period, but I chose to signify < and > because it worked better mnemonically.

Oh okay, I see. Perhaps it should be changed then?


> btw, you thought about joining a text mode art group such as Blocktronics? I really liked that free-fall piece you created for LayerOne!

Thanks for the compliment :)
I've thought about joining an artgroup, and I did get contacted by FUEL quite recently, but I haven't really made any final decisions on that yet. I'm going to participate as a guest for now, as I'm a bit worried it may take up a lot of my time (I'm working on several other projects besides ANSIart).
Currently I'm just focusing on trying to get better at drawing and becoming more well-known in the community.

**Comment by andyherbert** [comment]
Yeah, that's a good idea, I'll change it, but I'll keep this issue open until I commit any changes.

If you change your mind there's a Discord server that I can invite you to that has quite a few ANSI artists that can bounce ideas off, just let me know.

**Comment by luminde** [comment]
> If you change your mind there's a Discord server that I can invite you to that has quite a few ANSI artists that can bounce ideas off, just let me know.

That would be really appreciated, I've actually been looking for a way to contact other ANSI artists.

**Comment by andyherbert** [comment]
https://discord.gg/ynkuQU

**Comment by andyherbert** [comment]
https://discord.gg/nQpHfF

**Comment by andyherbert** [comment]
Fixed!
