### ISSUE TITLE
Enhancement to Guides

### ISSUE THREAD

**Issue by christianvozar** [blocktronics/moebius#82]
Love the 80x25 Guide. Would like to suggest enhancement:

- Modify "Toggle 80x25 Guides" to a Submenu of "Guides"
- Submenu items contains: 44x22 file-id.ans, 80x25 Classic, 80x40 Square, 80x50 Social Media

As an aside, 80x50 is the perfect size for instagram vertical posts which are the most popular and statistically get the most click-through. I think this would be the most valuable for those who post to IG like myself and Misfit.

**Comment by andyherbert** [comment]
implemented, if you pull the latest changes then you'll be able to test this.
