### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by DefinitelyZeusII** [blocktronics/moebius#88]
For some reason can't save another version of my ansi... I have saved AOD1.ans to AOD8. ans but it won't let me do AOD9.ans. Peace <3

**Comment by andyherbert** [comment]
There was an issue with Save As that was introduced in the last version, but if you update to the version pushed today it should work correctly!

**Comment by DefinitelyZeusII** [comment]
awesome :)

**Comment by andyherbert** [comment]
Also it has a Changelog now if you navigate to Help > Changelog
